# Generated by Django 4.1.7 on 2023-05-19 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_reports', '0002_completedwork_plannedwork_projectissues_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedwork',
            name='input1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='completedwork',
            name='input2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='completedwork',
            name='input3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='completedwork',
            name='input4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plannedwork',
            name='input1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plannedwork',
            name='input2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='plannedwork',
            name='input3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectissues',
            name='input1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectissues',
            name='input2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projectissues',
            name='input3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
