# Generated by Django 4.1.7 on 2023-05-19 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_reports', '0004_alter_projecttimeline_phase1_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttimeline',
            name='phase1_status',
            field=models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projecttimeline',
            name='phase2_status',
            field=models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress'), ('completed', 'Completed')], max_length=20),
        ),
        migrations.AlterField(
            model_name='projecttimeline',
            name='phase3_status',
            field=models.CharField(choices=[('not-started', 'Not Started'), ('in-progress', 'In Progress'), ('completed', 'Completed')], max_length=20),
        ),
    ]
