# Generated by Django 4.1.7 on 2023-05-19 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_reports', '0005_alter_projecttimeline_phase1_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plannedwork',
            name='action1_status',
            field=models.CharField(blank=True, choices=[('', 'Not Selected'), ('on-track', 'On Track'), ('not-started', 'Not Started')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plannedwork',
            name='action2_status',
            field=models.CharField(blank=True, choices=[('', 'Not Selected'), ('on-track', 'On Track'), ('not-started', 'Not Started')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='plannedwork',
            name='action3_status',
            field=models.CharField(blank=True, choices=[('', 'Not Selected'), ('on-track', 'On Track'), ('not-started', 'Not Started')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectissues',
            name='issue1_status',
            field=models.CharField(blank=True, choices=[('', 'Not Selected'), ('in-progress', 'In Progress'), ('not-started', 'Not Started')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectissues',
            name='issue2_status',
            field=models.CharField(blank=True, choices=[('', 'Not Selected'), ('in-progress', 'In Progress'), ('not-started', 'Not Started')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='projectissues',
            name='issue3_status',
            field=models.CharField(blank=True, choices=[('', 'Not Selected'), ('in-progress', 'In Progress'), ('not-started', 'Not Started')], max_length=20, null=True),
        ),
    ]
