# Generated by Django 4.1.7 on 2023-05-19 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress_reports', '0006_alter_plannedwork_action1_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='progressreport',
            name='report_title',
            field=models.CharField(default=datetime.date(2023, 5, 19), max_length=255),
            preserve_default=False,
        ),
    ]
