# Generated by Django 4.1.7 on 2023-03-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(verbose_name='Time In')),
                ('time_out', models.DateTimeField(verbose_name='Time_Out')),
                ('session_hours', models.DateTimeField(verbose_name='Session Hours')),
            ],
        ),
    ]
