# Generated by Django 4.1.7 on 2023-03-17 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSheet',
        ),
    ]
