# Generated by Django 4.2 on 2023-04-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sessions_timesheets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="pause_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="pause_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="paused",
            field=models.BooleanField(default=False),
        ),
    ]
