# Generated by Django 4.2 on 2023-04-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "sessions_timesheets",
            "0002_session_pause_end_session_pause_start_session_paused",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="time_in",
            field=models.DateTimeField(blank=True, verbose_name="Time In"),
        ),
    ]
