# Generated by Django 4.1.7 on 2023-05-02 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_timesheets', '0003_alter_session_time_in'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employer',
        ),
        migrations.DeleteModel(
            name='EmployerContact',
        ),
    ]
