# Generated by Django 4.1.7 on 2023-05-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sessions_timesheets', '0004_delete_employer_delete_employercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='total_pause_duration',
            field=models.DurationField(blank=True, null=True, verbose_name='Total Pause Duration'),
        ),
    ]
